const cheatsRaw = [
    { name: "Nursultan Client", displayName: "Nursultan Client", banner: "https://i.ytimg.com/vi/JbvxtOO-BTg/maxresdefault.jpg", icon: "https://i.pinimg.com/736x/84/b3/79/84b3792765a0c1d919a4b9718f132187.jpg", zipFile: "Nursultan_Client.zip", desc_ru: "Мощный бесплатный чит с визуалами премиум-уровня (ESP, Chams) и жесткими настройками под анархию.", fileType: ".exe", lastUpdate: "12.05.2026" },
    { name: "Catlavan Client", displayName: "Catlavan Client", banner: "https://i.ytimg.com/vi/8g3xpjXcKZY/maxresdefault.jpg", icon: "https://i.ytimg.com/vi/1aNQsM3EUrI/maxresdefault.jpg", zipFile: "Catlavan_Client.zip", desc_ru: "Легковесный и оптимизированный бесплатный чит для слабых ПК с минимальным просадом FPS и базовыми PvP-модулями.", fileType: ".exe", lastUpdate: "10.05.2026" },
    { name: "NightDLC Client", displayName: "NightDLC Client", banner: "https://i.ytimg.com/vi/3t2qq5ln9wo/maxresdefault.jpg", icon: "https://yandex-images.clstorage.net/QE5MO5105/8f18d9ju/VNHAOVXg_4joBjei1zHX5i_ZHW-pHHaI8SSi1OnCnoLkFSW0wmblgPhZAd0MC-gii8Rd3yjgN7qefL4flMotPnGFxQ2QlNvY2Eamhkbw89cvCclfaHlSaLXRgnTp8pjxBhJy0qCg13LPXsAoad79JiqwSRzLcWVZqZvJqccZ3miUkFBbFpMtPil1FDblsPWV_hh6rYs94hkXtsBzvIUooqYjU-MgcxfTLo0DavsuP5dNE5l8WHVECIrIm2hWSCz7xNECyXRxzs8IdkX0FMNHV335mL_KbjI4hJayg_3GC-HEwVGB4DKHg7-O0It7jf-W7_MIb1o1BxqZqUsIRJs8irVS42g0cuxuKEamZtTC1dUOiOqdKTyh-0Sm4jO8x4uR1hAwc3NTJwDv_OI4ueyMFUwCCQ-oJZQJ6hqaO4a6DEgEErNolyP8PTpFdcYGUTVm3KqLXwuuYMrUVBChzGf4QqTRUiIxUdWSTq1Q6ypOf2WPwMsOumcnuKkJuAnFS_6b9OIwyIagTF-KVPcGJ4N0JH0pG-9r_jPY1hWxk21H-YOk02KxAtKnAf0cUjqpLx0GvpG4DAjH1SspmqoqV7tMeEeRgJp0UX5dW9ZUphTip9U-2jl9-81DGpancxBuVZvj93IyMjJCxVMfbDHYuAwfhL7g6G2odzfpickaKbVaXVv2IkCo57GcDUhG1QZGE5ZnfUuZ_8v-IPpUNNIxH5QocldgodEws6Syze7TSWv9P6Ucw8l-W5R22DrIq2rlar0blmHQuSTxXA7K5gXltyMnlQ0KGy1aXXL41lYSca61yEPFghOTw3GGwBz-w9t5z65m_PIo7Ci0ZKpI6XtKhXmPaPfC0kuXQ149ShRXF5bgpDYdCnidWk_D2nbkYoI9lrqSJCJToeDgh1BevrGJWf-v5M0i-vy7JnYKyFtoWGdJ3os2gBLblODczEg0ZcRHsmemrLq4vwrMkzq2JOJBD-Q7U", zipFile: "Night_DLC.zip", desc_ru: "Приватный чит для жесткого PvP и анархии. Высокая оптимизация, KillAura, AutoTotem.", fileType: ".exe", lastUpdate: "15.05.2026" },
    { name: "Dimasik Client", displayName: "Dimasik Client", banner: "https://i.ytimg.com/vi/Nds9caAz40g/maxresdefault.jpg", icon: "https://yt3.googleusercontent.com/OBOj63_ZVyF_9w-QnVnTDzHEo2OFJY5oJcui6Xz7h27f9NzOlyzBDMfDBtw1amfDQnUJPV3t0g0=s900-c-k-c0x00ffffff-no-rj", zipFile: "Dimasik_Client.zip", desc_ru: "Русскоязычный клиент от блогера Dimasik. Яркий интерфейс, ESP, трейсеры, обход античитов СНГ.", fileType: ".jar", lastUpdate: "14.05.2026" },
    { name: "Celestial Client", displayName: "Celestial Client", banner: "https://i.ytimg.com/vi/SVbw7C1ZwKw/maxresdefault.jpg", icon: "https://i.ibb.co/Y79yCWCJ/celestial-logo.jpg", zipFile: "Celestial_Client.zip", desc_ru: "Премиальный приватный софт с уникальным дизайном интерфейса, автоматическим ливанием от проверок и NoClip.", fileType: ".exe", lastUpdate: "09.05.2026" },
    { name: "Monoton Client", displayName: "Monoton Client", banner: "https://i.ytimg.com/vi/YRpZyyd5NhI/maxresdefault.jpg", icon: "https://images.steamusercontent.com/ugc/9364292933957187456/62A3E3290BA57D7041A591EE1E6B41B4F56DEAD9/?imw=637&imh=358&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=true", zipFile: "Monoton_Client.zip", desc_ru: "Стильный бесплатный софт с акцентом на полную кастомизацию HUD, шрифтов и улучшенной функцией Velocity.", fileType: ".exe", lastUpdate: "11.05.2026" },
    { name: "Minced Client", displayName: "Minced Client", banner: "https://i.ytimg.com/vi/idWwsz2rzDg/maxresdefault.jpg", icon: "https://i.ibb.co/xt4yKssB/mincedlogo.jpg", zipFile: "Minced_Client.zip", desc_ru: "Популярный бесплатный хелпер для анархических серверов с отличной оптимизацией, стабильной KillAura и удобным ClickGUI.", fileType: ".exe", lastUpdate: "13.05.2026" },
    { name: "Arbuz Client", displayName: "Arbuz Client", banner: "https://i.ytimg.com/vi/QyvrO8v3UpA/maxresdefault.jpg", icon: "https://cdn.payga.me/offers/2025/8/12/48251/356158/7d93b23f4283f20f29f571bb249457de.image.jpg", zipFile: "Arbuz_Client.zip", desc_ru: "Простой и эффективный бесплатный хелпер с интуитивным меню, идеально подходящий для новичков.", fileType: ".exe", lastUpdate: "08.05.2026" },
    { name: "WexSide Client", displayName: "WexSide Client", banner: "https://i.ytimg.com/vi/BLMjBV46-88/hqdefault.jpg", icon: "https://avatars.mds.yandex.net/i?id=19510db354426b788822fd46eeb8f9b26d3e6f4a-5233110-images-thumbs&n=13", zipFile: "Wexside_Client.zip", desc_ru: "Топовый приватный софт для обходов античитов Matrix и Vulcan с плавными анимациями и кастомным TargetHUD.", fileType: ".exe", lastUpdate: "14.05.2026" },
    { name: "Haruka Client", displayName: "Haruka Client", banner: "https://i.ytimg.com/vi/0Uh1aQlgqe4/maxresdefault.jpg", icon: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMQLjM3gNXxhUr1D6KivMcOfO-hxI9OtVvSw&s", zipFile: "Haruka_Client.zip", desc_ru: "Популярный бесплатный софт в яркой аниме-стилистике с пробивным Reach, авто-блокхитом и быстрым лутом.", fileType: ".jar", lastUpdate: "12.05.2026" },
    { name: "Venus Client", displayName: "Venus Client", banner: "https://i.ytimg.com/vi/GSp6EBmjccw/maxresdefault.jpg", icon: "https://i.ytimg.com/vi/XMa1jXEB4qg/sddefault.jpg", zipFile: "Venus_Client.zip", desc_ru: "Полнофункциональная премиум-версия софта Venus с максимальным спектром настроек хитбоксов и моментальным авто-реконнектом.", fileType: ".exe", lastUpdate: "15.05.2026" },
    { name: "Delta Client", displayName: "Delta Client", banner: "https://i.ytimg.com/vi/_7Rwjkl4ca4/maxresdefault.jpg", icon: "https://images.steamusercontent.com/ugc/10532112875691339063/E117C260184D692FD75FB5E870B171DEA5C0C495/?imw=512&&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false", zipFile: "Delta_Client.zip", desc_ru: "Приватный чит премиум-класса с уникальными алгоритмами наводки и автоматизацией большинства PvP-процессов.", fileType: ".exe", lastUpdate: "13.05.2026" },
    { name: "Expensive Upgrade", displayName: "Expensive Upgrade", banner: "https://i.ytimg.com/vi/ObC1smEWli0/maxresdefault.jpg", icon: "https://yt3.googleusercontent.com/rRcBK-ENrNG8cbSmtrwGx5xn0ZM2FSZMQJKj5FycKQz1o53dQPsS
